Add thank-you post-donation page
TampaDevs/tampadevs-original-site pull request #119
Opened 2023-09-05 20:36 UTC by ebanner

Closes #97 

This PR adds a post-donation thank you landing page that we redirect from after a donation on opencollective

<img width="923" alt="image" src="https://github.com/TampaDevs/tampadevs/assets/2068912/0fc94b1b-c541-4cd0-bcb2-4468f00906e0">

# TODO

- [ ] Append `&redirect=https://www.tampadevs.com/thank-you` to `https://go.tampa.dev/donate` via [go](https://github.com/TampaDevs/go.tampa.dev)

# Extra little things

- [ ] Review thank you content (current content is chatGPT generated)
- [ ] Review thank you styling
- [ ] remove about page references (current thank you page is copied over from about page)

2023-09-06 15:02 UTC, chtzvt commented
Great job on this, @ebanner! 

Would it be possible to add an image above the text, as well? I feel like that'd tie the visuals and the messaging together well.

Here are some candidates:

- [Option 1](http://cdn.mcauto-images-production.sendgrid.net/c8a480076043ee31/196747ed-a786-434e-b303-5171dee7f859/3631x1393.jpg)
- [Option 2](http://cdn.mcauto-images-production.sendgrid.net/c8a480076043ee31/46b1b3ff-b825-42db-85f2-406a82271c24/3247x2072.jpg)
- [Option 3](http://cdn.mcauto-images-production.sendgrid.net/c8a480076043ee31/4bdcb374-8ce7-4107-b296-236bd24740ac/5332x3000.jpg)

2023-09-06 15:05 UTC, chtzvt commented on src/thank-you/index.njk
> +  <link rel="stylesheet" href="https://unpkg.com/flickity@2/dist/flickity.min.css">
Since this page doesn't have the homepage sliders, I'd recommend removing Flickity's CSS/JS.

2023-09-06 15:05 UTC, chtzvt commented on src/thank-you/index.njk
> +<script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js"></script>
Since this page doesn't have the homepage sliders, I'd recommend removing Flickity's CSS/JS.

2023-09-06 15:05 UTC, chtzvt commented on src/thank-you/index.njk
> +  new Flickity('.slider__past-events', {
Since this page doesn't have the homepage sliders, I'd recommend removing Flickity's CSS/JS.

2023-09-16 21:22 UTC, ebanner commented
Alright, I've been playing around for a while. I'm at the point where I could probably use some feedback

https://github.com/TampaDevs/tampadevs/assets/2068912/bce04ad2-9ae8-4ed2-95fe-86e349a79a36

2023-09-16 21:59 UTC, manuelosorio commented
@ebanner 
This is looking good so far. If possible, push your current changes that way I can preview this in my own devices as well. 

I do have a suggestion.

Since you are using a two-column grid for the image and text layout I suggest changing the max-width of this page container. Maybe creating a new class called something like container--1200 (or whatever the max width is). That should allow for you to use a breakpoint at a smaller width. If anything, have the change to column happen a little bit earlier

2023-09-17 19:40 UTC, manuelosorio requested changes
Good job on this. There are just a few things that need updating.

2023-09-17 19:40 UTC, manuelosorio commented on src/_includes/blocks/head.njk
> +      margin: 20px 150px 40px;
The margin left right of 150px is too much on mobile devices. 
You could something like:
```css
.thank-you-page {
    width: 90%;
    max-width: 1200px;
    margin: 20px auto 40px;
}
```
That would a very similar outcome and would easily work on smaller devices. 


![image](https://github.com/TampaDevs/tampadevs/assets/10530584/16f6dacd-597b-4a6d-845b-1b3afa5e1bb7)

2023-09-17 19:40 UTC, manuelosorio commented on src/thank-you/index.njk
> +  {# <div class="thank-you-image-container">
Cleanup: Remove commented out code

2023-09-17 19:40 UTC, manuelosorio commented on src/thank-you/index.njk
> +      <div class="xs:ml--20 md:ml--40"></div>
Cleanup

2023-09-17 19:40 UTC, manuelosorio commented on src/_includes/blocks/head.njk
> +      margin: 20px 150px 40px;
Also, if possible, use rem instead of px.

2023-09-17 19:40 UTC, manuelosorio commented on src/thank-you/index.njk
> +    <img src="/_assets/img/thank-you/3631x1393.jpg" alt="Header Image">
Alt attribute should be more descriptive for screen readers.

2023-09-25 20:35 UTC, manuelosorio commented on src/_includes/layouts/home.njk
> +      <a class="sponsor-button td-alert-banner" href="https://go.tampa.dev/donate-and-redirect">Donate</a>
Please change back to old link. Those are provided by separate URL redirector service we have. https://go.tampa.dev/donate leads to open collective.

2023-09-25 20:38 UTC, manuelosorio requested changes
This looks good to me. There is only thing that needs to be changed which is the donate link.

2023-09-25 21:10 UTC, ebanner commented on src/_includes/layouts/home.njk
> +      <a class="sponsor-button td-alert-banner" href="https://go.tampa.dev/donate-and-redirect">Donate</a>
@manuelosorio Just to be clear, you are aware we need to make a modification in the URL redirector service either way, right? So the user gets [redirected back](https://docs.opencollective.com/help/contributing/development/post-donation-redirect) to tampadevs.com (currently that's not happening)

2023-09-25 21:10 UTC, ebanner commented on src/_includes/layouts/home.njk
> +      <a class="sponsor-button td-alert-banner" href="https://go.tampa.dev/donate-and-redirect">Donate</a>
The two ways to do it as I see it

- Modify https://go.tampa.dev/donate to append `&redirect=https://www.tampadevs.com/thank-you` on the end of it so the user gets redirected back
- Add a new entry https://go.tampa.dev/donate-and-redirect with that bit appended on at the end

I'm in favor of the second approach because there's no downtime associated with it

2023-09-25 21:37 UTC, manuelosorio commented on src/_includes/layouts/home.njk
> +      <a class="sponsor-button td-alert-banner" href="https://go.tampa.dev/donate-and-redirect">Donate</a>
Yes, i've talked with Charlton he is going to change where /donate url points to. The url you set is not an endpoint we have that's why it redirects to Tampa Devs and never goes to OpenCollective.

2023-09-25 21:53 UTC, ebanner commented on src/_includes/layouts/home.njk
> +      <a class="sponsor-button td-alert-banner" href="https://go.tampa.dev/donate-and-redirect">Donate</a>
So, if you've talked to Charlton and you guys would like to keep it at donate, that's fine with me 👍

However, just want to make sure we're on the same page

> The url you set is not an endpoint we have that's why it redirects to Tampa Devs and never goes to OpenCollective

Yes, there is no entry for `donate-and-redirect`. We would need to add it go go.tampa.dev for it to work. Redirecting is the expected behavior right now

2023-09-25 21:57 UTC, ebanner commented on src/_includes/layouts/home.njk
> +      <a class="sponsor-button td-alert-banner" href="https://go.tampa.dev/donate-and-redirect">Donate</a>
For completeness, I'd like to lay out a zero downtime solution, with the ultimate result being `/donate`

1. Add `/donate-and-redirect` entry to https://go.tampa.dev/
2. Push website code with `/donate-and-redirect` link
3. Modify `/donate` to append redirect bit
4. Push website code with `/donate` link
5. Delete `/donate-and-redirect` entry from https://go.tampa.dev/

2023-09-26 14:46 UTC, chtzvt commented on src/_includes/layouts/home.njk
> +      <a class="sponsor-button td-alert-banner" href="https://go.tampa.dev/donate-and-redirect">Donate</a>
Hey folks, 

I've updated our https://go.tampa.dev/donate link to include the redirect to the new thank you page. I'm not particularly worried about a post-donation redirect leading to a 404 before we merge these changes in, since we're very close to doing so.

2023-09-26 14:49 UTC, chtzvt commented on src/_includes/layouts/home.njk
> +      <a class="sponsor-button td-alert-banner" href="https://go.tampa.dev/donate-and-redirect">Donate</a>
Both /donate and /donate-and-redirect match on the updated shortlink. I'd still like to update the shortlink on this page to /donate (since that's our canonical donation URL), though.

2023-09-26 15:07 UTC, ebanner commented on src/_includes/layouts/home.njk
> +      <a class="sponsor-button td-alert-banner" href="https://go.tampa.dev/donate-and-redirect">Donate</a>
Ah, that's a good point. I didn't realize updating the URL entry wouldn't break linking out to opencollective

I went ahead and changed it back to the shortlink

2023-09-26 15:07 UTC, ebanner commented on src/_includes/layouts/home.njk
> +      <a class="sponsor-button td-alert-banner" href="https://go.tampa.dev/donate-and-redirect">Donate</a>
Thanks for doing that @chtzvt!

2023-09-26 15:10 UTC, manuelosorio approved these changes
LGTM!

2023-09-26 15:11 UTC, ebanner commented
🙌

2023-09-26 15:15 UTC, merged