added Slack logo to join chat - experimental
TampaDevs/tampadevs-original-site pull request #35
Opened 2022-11-15 00:00 UTC by haridira

2022-11-17 03:01 UTC, vincentntang commented
doesn't appear to be working from the cloudflare URL preview
![image](https://user-images.githubusercontent.com/10290348/202344383-03be2ac1-34ab-434a-ba47-b7ab72a3766f.png)

2022-11-17 03:07 UTC, vincentntang commented on src/index.njk
> -        Join Chat
I would use something like this

```
<div class="cta-wrapper">
  <img src={put_where_it_comes_from_here}/>
  <span>Join Chat</span>
 </div>
 ```
 
 For `.cta-wrapper` class, it would look like so:
 
 ```
 .cta-wrapper {
 display: flex;
 align-items: center;
 }
 ```

2022-12-05 19:17 UTC, haridira commented
Added Slack icon image

2022-12-05 19:26 UTC, haridira commented
moved to the CTA towards the bottom

2022-12-05 22:59 UTC, vincentntang commented
could you vertically center the logo? and add the other logo to the card component too

![image](https://user-images.githubusercontent.com/10290348/205761187-30156ce7-678f-4968-89cb-c80bd56e6174.png)

2022-12-05 23:00 UTC, vincentntang commented on src/index.njk
> +        Join Chat <i class="fa-brands fa-slack"></i>
so you still need to fix this here. The font-awesome library isn't being rendered on the page since you haven't installed it on the repo, so it doesn't show up. You still would want to remove this anyways

2022-12-05 23:01 UTC, vincentntang commented on .eleventy.js
> +    "node_modules/aos/dist/fontawesome.js": "https://kit.fontawesome.com/f8f49d4cdb.js"
you'll want to remove this line. When you use `node_modules` you also need to update `package.json` to reflect where that package is installed. 

this line currently doesn't do anything since its not pulling from any installed modules

and you also don't want this line anyways

2022-12-05 23:04 UTC, vincentntang commented on src/index.njk
> +        Join Chat <i class="fa-brands fa-slack"></i>
this should say something like
`<span><img class="social-icon" src="/_assets/misc/icons/slack.svg" alt="slack">Join Chat </span>` or something like that

2022-12-06 01:26 UTC, haridira commented on src/index.njk
> +        Join Chat <i class="fa-brands fa-slack"></i>
Yes! This is what I did for the other button (I edited the home file by mistake instead of index since we have a similar button there as well)

2022-12-06 01:27 UTC, haridira commented on src/index.njk
> +        Join Chat <i class="fa-brands fa-slack"></i>
Font awesome was there from a previous time and forgot to clean it up earlier (done now!). Yes I tried to install it like you said, I just think it wasn't the right location

2022-12-06 01:28 UTC, haridira commented on .eleventy.js
> +    "node_modules/aos/dist/fontawesome.js": "https://kit.fontawesome.com/f8f49d4cdb.js"
Noted. Cleaned it up already

2022-12-07 15:58 UTC, ctrezevant commented
Looks like it's still not quite centered (as of `c8ddb0c`/https://65203887.tampadevs.pages.dev). 

<img width="835" alt="Screenshot 2022-12-07 at 10 57 46" src="https://user-images.githubusercontent.com/7227500/206227786-f7b16ca0-ff71-4a3f-af2d-91328c8f1096.png">

2022-12-07 15:59 UTC, ctrezevant commented
Also @vincentntang N.B. I've uninstalled Netlify on this org since CF Pages is handling builds/deployment now.

2023-01-13 01:28 UTC, manuelosorio requested changes
Good work @haridira I left a review on the nav. Once you implement those changes the icon should be centered properly. Let me know if you have any questions or need any help.

2023-01-13 01:28 UTC, manuelosorio commented on src/_assets/scss/_nav.scss
> +.js-moveto {
Inside of the [style.scss](https://github.com/TampaDevs/tampadevs/blob/master/src/_assets/scss/style.scss) there is a declaration already selecting the each of the CTAs  `.td-header__ctas a`

Due to specificity the declaration made to the display property inside of `js-moveto` class.

My suggestion would be to change the display property in `.td-header__ctas` a from inline-block to inline-flex and align-items: center inside of it. That way you can also avoid adding styles to the js-moveto.

2023-01-16 16:28 UTC, manuelosorio commented
A new fresh branch and pull request was created for this change.

2023-01-16 16:28 UTC, closed without merging