Update slack link URL on homepage #60
TampaDevs/tampadevs-original-site pull request #61
Opened 2023-01-25 17:38 UTC by Priyanshii677

2023-01-25 18:00 UTC, manuelosorio requested changes
Thank you for the pull request. The links just need a slight update to work properly.

2023-01-25 18:00 UTC, manuelosorio commented on src/_includes/blocks/footer.njk
> +      <li><a href="go.tampa.dev/slack" target="_blank" rel="noopener"><img class="social-icon" src="/_assets/misc/icons/slack.svg" alt="Slack"/></a></li>
When this is clicked user will be sent to http://tampadevs.com/go.tampa.dev/slack
to fix that issue please change it to https://go.tampa.dev/slack

2023-01-25 18:00 UTC, manuelosorio commented on src/index.njk
> +        href="go.tampa.dev/slack"
This one will need that change too.

2023-01-25 18:07 UTC, manuelosorio commented
The navigation slack icon will also need the new url for slack.

That can be updated in this file. https://github.com/TampaDevs/tampadevs/blob/master/src/_data/basics.json

2023-01-25 22:04 UTC, chtzvt commented
Great work @Priyanshii677! With the minor tweaks suggested by Manuel we'll be able to merge this immediately.

2023-01-26 10:46 UTC, Priyanshii677 commented
Here are the new changes @manuelosorio

2023-01-26 13:01 UTC, manuelosorio approved these changes
Thank you for the changes.

2023-01-26 13:02 UTC, merged